print "Weighted marks for assigment1 is:" 
print "Weighted marks for assigment2 is:" 
print "Total Weighted marks for assigment2 is:" 
print "Weighted marks for final exam is:" 
print "Total Weighted marks for subject is:"
print "bonus marks:"
print "total marks with bonus :"
print "Goodbye"
print "kiran reddy kancharla kiran"
